# Generated by Django 2.1.3 on 2018-11-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('totalsum', models.CharField(max_length=100, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('categoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюдо',
            },
        ),
        migrations.CreateModel(
            name='MealsToOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, null=True, verbose_name='Количество')),
                ('mealsid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Meals', verbose_name='Питание')),
            ],
            options={
                'verbose_name': 'Распределение по заказам',
                'verbose_name_plural': 'Распределение по заказам',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablesname', models.CharField(max_length=100, verbose_name='Название стола')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('mealsid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Meals', verbose_name='Питание')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=15, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Процент',
                'verbose_name_plural': 'Проценты',
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='in progress', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=8, verbose_name='Пароль')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('dateofadd', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('roleid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Roles', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='statusid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Statuses', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='orders',
            name='tablesid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Tables', verbose_name='Стол'),
        ),
        migrations.AddField(
            model_name='orders',
            name='waiterid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Users', verbose_name='Официант'),
        ),
        migrations.AddField(
            model_name='mealstoorders',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Orders', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='checks',
            name='mealsid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Meals', verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Orders', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='checks',
            name='percentage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.ServicePercentage', verbose_name='Процент'),
        ),
        migrations.AddField(
            model_name='category',
            name='departmentsid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Departments', verbose_name='Отдел'),
        ),
    ]
