# Generated by Django 2.1.3 on 2018-11-27 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='waiterid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Официант'),
        ),
        migrations.AddField(
            model_name='mealstoorders',
            name='mealsid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Meals', verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='mealstoorders',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Orders', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='meals',
            name='categoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='checks',
            name='mealsid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Meals', verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Orders', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='checks',
            name='percentage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.ServicePercentage', verbose_name='Процент'),
        ),
        migrations.AddField(
            model_name='category',
            name='departmentsid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Departments', verbose_name='Отдел'),
        ),
    ]
